const TaskActionTypes = {
  GET_TASKS_REQUEST: "GET_TASKS_REQUEST",
  GET_TASKS_RESPONSE: "GET_TASKS_RESPONSE",
  GET_TASKS_RESPONSE_CLEAR: "GET_TASKS_RESPONSE_CLEAR",

  GET_TASK_BY_ID_REQUEST: "GET_TASK_BY_ID_REQUEST",
  GET_TASK_BY_ID_RESPONSE: "GET_TASK_BY_ID_RESPONSE",
  GET_TASK_BY_ID_RESPONSE_CLEAR: "GET_TASK_BY_ID_RESPONSE_CLEAR",

  POST_TASK_REQUEST: "POST_TASK_REQUEST",
  POST_TASK_RESPONSE: "POST_TASK_RESPONSE",
  POST_TASK_RESPONSE_CLEAR: "POST_TASK_RESPONSE_CLEAR",

  PUT_TASK_REQUEST: "PUT_TASK_REQUEST",
  PUT_TASK_RESPONSE: "PUT_TASK_RESPONSE",
  PUT_TASK_RESPONSE_CLEAR: "PUT_TASK_RESPONSE_CLEAR",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_RESPONSE: "DELETE_TASK_RESPONSE",
  DELETE_TASK_RESPONSE_CLEAR: "DELETE_TASK_RESPONSE_CLEAR",
};

export default TaskActionTypes;
